services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "8000:8000"
    networks:
      - app-network
    env_file:
      - ./website/.env.prod

  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "4324:3000"
    depends_on:
      - backend
    networks:
      - app-network
    env_file:
      - ./website/.env.prod
    volumes:
      - node_modules:/app/node_modules

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    networks:
      - app-network
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - ./website/.env.prod

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  node_modules: {}
